#Sources
:sources:
  Product:
    :poll_interval: 300

:development:
  :licensefile: settings/license.key
  :redis: 192.168.2.23:6379
  :syncserver: http://192.168.2.23:9292/api/application/
  :push_server: http://someappname@192.168.2.23:8675/
  :api_token: my-rhoconnect-token
:test:
  :licensefile: settings/license.key
  :redis: 192.168.2.23:6379
  :syncserver: http://192.168.2.23:9292/api/application/
  :push_server: http://someappname@192.168.2.23:8675/
  :api_token: my-rhoconnect-token
:production:
  :licensefile: settings/license.key
  :redis: 192.168.2.23:6379
  :syncserver: http://192.168.2.23:9292/api/application/
  :push_server: http://someappname@192.168.2.23:8675/
